dist: xenial

language: ruby

git:
  depth: 200

rvm:
  - 2.3.3

before_install:
  - sudo apt-get install -y libpango1.0-dev ghostscript fonts-lyx
  - gem install asciidoctor -v 2.0.16
  - gem install coderay -v 1.1.1
  - gem install rouge -v 3.19.0
  - gem install ttfunk -v 1.5.1
  - gem install asciidoctor-pdf -v 1.5.0
  - gem install asciidoctor-mathematical -v 0.3.5

script:
  - git describe --tags --dirty
  # This produces an error because travis-ci works with a "detached head".
  #- git symbolic-ref --short HEAD
  - make -O -j 5 api c env ext cxx4opencl

#after_success:
#  - cd out
#  - git init
#  - git config user.name "${GH_USER_NAME}"
#  - git config user.email "${GH_USER_EMAIL}"
#  - git add html pdf ; git commit -m "Deploy to Github Pages"
#  - git push -f "https://${GH_TOKEN}@${GH_REF}" master:gh-pages

after_success:
  - mkdir deploy
  - cp -R out/html out/pdf deploy

deploy:
  verbose: true
  provider: pages
  local_dir: deploy
  skip_cleanup: true
  github_token: $GH_TOKEN
  #keep_history: true
  on:
    #branch: master
    branch: travis-ci
